[project]
authors = ["John Quid <john@quid.io>"]
entry = "main.sw"
license = "BSL 1.1"
name = "QD"

[dependencies]
libraries = { path = "../../libraries" }
signed_integers = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }
fixed_point = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }

