[project]
authors = ["John Quid <john@quid.io>"]
entry = "interface.sw"
license = "BSL 1.1"
name = "libraries"

[dependencies]
# signed_integers = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }
# fixed_point = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }